AGLPets/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AGLPets.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AGLPets/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.Xml;
using System.Threading.Tasks;
using AGLPetBALInterfaces;
using AGLPetWebInterfaces;
using AGLWebModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AGLPets.Pages
{
    public class IndexModel : PageModel, IPeoplePage
    {
        private readonly ILogger<IndexModel> logger;
        private readonly IPetService petService;

        [BindProperty]
        public List<GenderPetNameModel> genderPetName { get;set;}
        public IndexModel(ILogger<IndexModel> logger, IPetService petService)
        {
            this.logger = logger;
            this.petService = petService;
        }               

        public void OnGet()
        {        
        }
      
        public async Task OnPostPetsOwnerGender()
        {
             await GetPets();
        }
        public async Task GetPets()
        {
            genderPetName = await this.petService.GetPets();
        }
    }
}

AGLPets/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome to AGL Pets</h1>
       
        <form method="post" asp-page="Index">
            <button type="submit" class="btn btn-primary" asp-page-handler="PetsOwnerGender">Get Pets by Owner Gender</button>
        </form>
    </div>
    <div class="offset-4">
        @if(Model.genderPetName != null && Model.genderPetName.Any())
        {
            @foreach(var el in Model.genderPetName)
            {
                <span><strong>@el.Gender</strong></span>
                <ul>
                    @foreach(var name in el.PetNames)
                    {
                        <li>@name</li>
                    }
                </ul>
                <br />
            }
        }
    </div>

AGLPets/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AGLPets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AGLPets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AGLPets 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>